# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('married', models.BooleanField(default=False)),
                ('introduce', models.TextField()),
                ('addTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ('-addTime',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('type', models.IntegerField()),
                ('updateTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('count', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Author')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ('status',),
            },
        ),
    ]
